package com.hoolink.manage.base.dao.model;

import java.io.Serializable;

public class ManageMenu implements Serializable {
    /**
     * <pre>
     * 主键
     * 表字段 : manage_menu.id
     * </pre>
     */
    private Long id;

    /**
     * <pre>
     * 名称
     * 表字段 : manage_menu.menu_name
     * </pre>
     */
    private String menuName;

    /**
     * <pre>
     * 链接地址
     * 表字段 : manage_menu.url
     * </pre>
     */
    private String url;

    /**
     * <pre>
     * 菜单码
     * 表字段 : manage_menu.menu_code
     * </pre>
     */
    private String menuCode;

    /**
     * <pre>
     * 同级菜单排列顺序(数值越小，优先级越高)
     * 表字段 : manage_menu.priority
     * </pre>
     */
    private Integer priority;

    /**
     * <pre>
     * 父级ID
     * 表字段 : manage_menu.parent_id
     * </pre>
     */
    private Long parentId;

    /**
     * <pre>
     * 创建人
     * 表字段 : manage_menu.creator
     * </pre>
     */
    private Long creator;

    /**
     * <pre>
     * 修改人
     * 表字段 : manage_menu.updator
     * </pre>
     */
    private Long updator;

    /**
     * <pre>
     * 创建时间
     * 表字段 : manage_menu.created
     * </pre>
     */
    private Long created;

    /**
     * <pre>
     * 修改时间
     * 表字段 : manage_menu.updated
     * </pre>
     */
    private Long updated;

    /**
     * <pre>
     * 数据有效性
     * 表字段 : manage_menu.enabled
     * </pre>
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manage_menu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * 获取：主键
     * 表字段：manage_menu.id
     * </pre>
     *
     * @return manage_menu.id：主键
     */
    public Long getId() {
        return id;
    }

    /**
     * <pre>
     * 设置：主键
     * 表字段：manage_menu.id
     * </pre>
     *
     * @param id
     *            manage_menu.id：主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * <pre>
     * 获取：名称
     * 表字段：manage_menu.menu_name
     * </pre>
     *
     * @return manage_menu.menu_name：名称
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * <pre>
     * 设置：名称
     * 表字段：manage_menu.menu_name
     * </pre>
     *
     * @param menuName
     *            manage_menu.menu_name：名称
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * <pre>
     * 获取：链接地址
     * 表字段：manage_menu.url
     * </pre>
     *
     * @return manage_menu.url：链接地址
     */
    public String getUrl() {
        return url;
    }

    /**
     * <pre>
     * 设置：链接地址
     * 表字段：manage_menu.url
     * </pre>
     *
     * @param url
     *            manage_menu.url：链接地址
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * <pre>
     * 获取：菜单码
     * 表字段：manage_menu.menu_code
     * </pre>
     *
     * @return manage_menu.menu_code：菜单码
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * <pre>
     * 设置：菜单码
     * 表字段：manage_menu.menu_code
     * </pre>
     *
     * @param menuCode
     *            manage_menu.menu_code：菜单码
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode == null ? null : menuCode.trim();
    }

    /**
     * <pre>
     * 获取：同级菜单排列顺序(数值越小，优先级越高)
     * 表字段：manage_menu.priority
     * </pre>
     *
     * @return manage_menu.priority：同级菜单排列顺序(数值越小，优先级越高)
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * <pre>
     * 设置：同级菜单排列顺序(数值越小，优先级越高)
     * 表字段：manage_menu.priority
     * </pre>
     *
     * @param priority
     *            manage_menu.priority：同级菜单排列顺序(数值越小，优先级越高)
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * <pre>
     * 获取：父级ID
     * 表字段：manage_menu.parent_id
     * </pre>
     *
     * @return manage_menu.parent_id：父级ID
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * <pre>
     * 设置：父级ID
     * 表字段：manage_menu.parent_id
     * </pre>
     *
     * @param parentId
     *            manage_menu.parent_id：父级ID
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * <pre>
     * 获取：创建人
     * 表字段：manage_menu.creator
     * </pre>
     *
     * @return manage_menu.creator：创建人
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * <pre>
     * 设置：创建人
     * 表字段：manage_menu.creator
     * </pre>
     *
     * @param creator
     *            manage_menu.creator：创建人
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * <pre>
     * 获取：修改人
     * 表字段：manage_menu.updator
     * </pre>
     *
     * @return manage_menu.updator：修改人
     */
    public Long getUpdator() {
        return updator;
    }

    /**
     * <pre>
     * 设置：修改人
     * 表字段：manage_menu.updator
     * </pre>
     *
     * @param updator
     *            manage_menu.updator：修改人
     */
    public void setUpdator(Long updator) {
        this.updator = updator;
    }

    /**
     * <pre>
     * 获取：创建时间
     * 表字段：manage_menu.created
     * </pre>
     *
     * @return manage_menu.created：创建时间
     */
    public Long getCreated() {
        return created;
    }

    /**
     * <pre>
     * 设置：创建时间
     * 表字段：manage_menu.created
     * </pre>
     *
     * @param created
     *            manage_menu.created：创建时间
     */
    public void setCreated(Long created) {
        this.created = created;
    }

    /**
     * <pre>
     * 获取：修改时间
     * 表字段：manage_menu.updated
     * </pre>
     *
     * @return manage_menu.updated：修改时间
     */
    public Long getUpdated() {
        return updated;
    }

    /**
     * <pre>
     * 设置：修改时间
     * 表字段：manage_menu.updated
     * </pre>
     *
     * @param updated
     *            manage_menu.updated：修改时间
     */
    public void setUpdated(Long updated) {
        this.updated = updated;
    }

    /**
     * <pre>
     * 获取：数据有效性
     * 表字段：manage_menu.enabled
     * </pre>
     *
     * @return manage_menu.enabled：数据有效性
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * <pre>
     * 设置：数据有效性
     * 表字段：manage_menu.enabled
     * </pre>
     *
     * @param enabled
     *            manage_menu.enabled：数据有效性
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}