package com.hoolink.manage.base.dao.model;

import java.io.Serializable;

public class ManageDepartment implements Serializable {
    /**
     * <pre>
     * 主键
     * 表字段 : manage_department.id
     * </pre>
     */
    private Long id;

    /**
     * <pre>
     * 名称
     * 表字段 : manage_department.dept_name
     * </pre>
     */
    private String name;

    /**
     * <pre>
     * 1-公司 2-部门 3-小组
     * 表字段 : manage_department.dept_type
     * </pre>
     */
    private Byte deptType;

    /**
     * <pre>
     * 父级ID
     * 表字段 : manage_department.parent_id
     * </pre>
     */
    private Long parentId;

    /**
     * <pre>
     * 创建人
     * 表字段 : manage_department.creator
     * </pre>
     */
    private Long creator;

    /**
     * <pre>
     * 修改人
     * 表字段 : manage_department.updator
     * </pre>
     */
    private Long updator;

    /**
     * <pre>
     * 创建时间
     * 表字段 : manage_department.created
     * </pre>
     */
    private Long created;

    /**
     * <pre>
     * 修改时间
     * 表字段 : manage_department.updated
     * </pre>
     */
    private Long updated;

    /**
     * <pre>
     * 数据有效性
     * 表字段 : manage_department.enabled
     * </pre>
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manage_department
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * 获取：主键
     * 表字段：manage_department.id
     * </pre>
     *
     * @return manage_department.id：主键
     */
    public Long getId() {
        return id;
    }

    /**
     * <pre>
     * 设置：主键
     * 表字段：manage_department.id
     * </pre>
     *
     * @param id
     *            manage_department.id：主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * <pre>
     * 获取：名称
     * 表字段：manage_department.dept_name
     * </pre>
     *
     * @return manage_department.dept_name：名称
     */
    public String getName() {
        return name;
    }

    /**
     * <pre>
     * 设置：名称
     * 表字段：manage_department.dept_name
     * </pre>
     *
     * @param name
     *            manage_department.dept_name：名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * <pre>
     * 获取：1-公司 2-部门 3-小组
     * 表字段：manage_department.dept_type
     * </pre>
     *
     * @return manage_department.dept_type：1-公司 2-部门 3-小组
     */
    public Byte getDeptType() {
        return deptType;
    }

    /**
     * <pre>
     * 设置：1-公司 2-部门 3-小组
     * 表字段：manage_department.dept_type
     * </pre>
     *
     * @param deptType
     *            manage_department.dept_type：1-公司 2-部门 3-小组
     */
    public void setDeptType(Byte deptType) {
        this.deptType = deptType;
    }

    /**
     * <pre>
     * 获取：父级ID
     * 表字段：manage_department.parent_id
     * </pre>
     *
     * @return manage_department.parent_id：父级ID
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * <pre>
     * 设置：父级ID
     * 表字段：manage_department.parent_id
     * </pre>
     *
     * @param parentId
     *            manage_department.parent_id：父级ID
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * <pre>
     * 获取：创建人
     * 表字段：manage_department.creator
     * </pre>
     *
     * @return manage_department.creator：创建人
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * <pre>
     * 设置：创建人
     * 表字段：manage_department.creator
     * </pre>
     *
     * @param creator
     *            manage_department.creator：创建人
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * <pre>
     * 获取：修改人
     * 表字段：manage_department.updator
     * </pre>
     *
     * @return manage_department.updator：修改人
     */
    public Long getUpdator() {
        return updator;
    }

    /**
     * <pre>
     * 设置：修改人
     * 表字段：manage_department.updator
     * </pre>
     *
     * @param updator
     *            manage_department.updator：修改人
     */
    public void setUpdator(Long updator) {
        this.updator = updator;
    }

    /**
     * <pre>
     * 获取：创建时间
     * 表字段：manage_department.created
     * </pre>
     *
     * @return manage_department.created：创建时间
     */
    public Long getCreated() {
        return created;
    }

    /**
     * <pre>
     * 设置：创建时间
     * 表字段：manage_department.created
     * </pre>
     *
     * @param created
     *            manage_department.created：创建时间
     */
    public void setCreated(Long created) {
        this.created = created;
    }

    /**
     * <pre>
     * 获取：修改时间
     * 表字段：manage_department.updated
     * </pre>
     *
     * @return manage_department.updated：修改时间
     */
    public Long getUpdated() {
        return updated;
    }

    /**
     * <pre>
     * 设置：修改时间
     * 表字段：manage_department.updated
     * </pre>
     *
     * @param updated
     *            manage_department.updated：修改时间
     */
    public void setUpdated(Long updated) {
        this.updated = updated;
    }

    /**
     * <pre>
     * 获取：数据有效性
     * 表字段：manage_department.enabled
     * </pre>
     *
     * @return manage_department.enabled：数据有效性
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * <pre>
     * 设置：数据有效性
     * 表字段：manage_department.enabled
     * </pre>
     *
     * @param enabled
     *            manage_department.enabled：数据有效性
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}