package com.hoolink.manage.base.dao.model;

import java.io.Serializable;

public class MiddleRoleMenu implements Serializable {
    /**
     * <pre>
     * 主键
     * 表字段 : middle_role_menu.id
     * </pre>
     */
    private Long id;

    /**
     * <pre>
     * 角色表ID
     * 表字段 : middle_role_menu.role_id
     * </pre>
     */
    private Long roleId;

    /**
     * <pre>
     * 菜单表ID
     * 表字段 : middle_role_menu.menu_id
     * </pre>
     */
    private Long menuId;

    /**
     * <pre>
     * 权限级别 1-只读 2-全部(读、写)
     * 表字段 : middle_role_menu.permission_flag
     * </pre>
     */
    private Integer permissionFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table middle_role_menu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * 获取：主键
     * 表字段：middle_role_menu.id
     * </pre>
     *
     * @return middle_role_menu.id：主键
     */
    public Long getId() {
        return id;
    }

    /**
     * <pre>
     * 设置：主键
     * 表字段：middle_role_menu.id
     * </pre>
     *
     * @param id
     *            middle_role_menu.id：主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * <pre>
     * 获取：角色表ID
     * 表字段：middle_role_menu.role_id
     * </pre>
     *
     * @return middle_role_menu.role_id：角色表ID
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * <pre>
     * 设置：角色表ID
     * 表字段：middle_role_menu.role_id
     * </pre>
     *
     * @param roleId
     *            middle_role_menu.role_id：角色表ID
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * <pre>
     * 获取：菜单表ID
     * 表字段：middle_role_menu.menu_id
     * </pre>
     *
     * @return middle_role_menu.menu_id：菜单表ID
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * <pre>
     * 设置：菜单表ID
     * 表字段：middle_role_menu.menu_id
     * </pre>
     *
     * @param menuId
     *            middle_role_menu.menu_id：菜单表ID
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * <pre>
     * 获取：权限级别 1-只读 2-全部(读、写)
     * 表字段：middle_role_menu.permission_flag
     * </pre>
     *
     * @return middle_role_menu.permission_flag：权限级别 1-只读 2-全部(读、写)
     */
    public Integer getPermissionFlag() {
        return permissionFlag;
    }

    /**
     * <pre>
     * 设置：权限级别 1-只读 2-全部(读、写)
     * 表字段：middle_role_menu.permission_flag
     * </pre>
     *
     * @param permissionFlag
     *            middle_role_menu.permission_flag：权限级别 1-只读 2-全部(读、写)
     */
    public void setPermissionFlag(Integer permissionFlag) {
        this.permissionFlag = permissionFlag;
    }
}