package com.hoolink.manage.base.dao.model;

import java.io.Serializable;

public class MiddleUserDepartment implements Serializable {
    /**
     * <pre>
     * 主键
     * 表字段 : middle_user_department.id
     * </pre>
     */
    private Long id;

    /**
     * <pre>
     * 用户表ID
     * 表字段 : middle_user_department.user_id
     * </pre>
     */
    private Long userId;

    /**
     * <pre>
     * 部门表ID
     * 表字段 : middle_user_department.dept_id
     * </pre>
     */
    private Long deptId;

    /**
     * <pre>
     * 部门密保等级(0-特级,1-一级,2-二级,3-三级,4-四级)
     * 表字段 : middle_user_department.encry_level_dept
     * </pre>
     */
    private Integer encryLevelDept;

    /**
     * <pre>
     * 同一用户不同部门区分标识
     * 表字段 : middle_user_department.diff_dept_group
     * </pre>
     */
    private String diffDeptGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table middle_user_department
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * 获取：主键
     * 表字段：middle_user_department.id
     * </pre>
     *
     * @return middle_user_department.id：主键
     */
    public Long getId() {
        return id;
    }

    /**
     * <pre>
     * 设置：主键
     * 表字段：middle_user_department.id
     * </pre>
     *
     * @param id
     *            middle_user_department.id：主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * <pre>
     * 获取：用户表ID
     * 表字段：middle_user_department.user_id
     * </pre>
     *
     * @return middle_user_department.user_id：用户表ID
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * <pre>
     * 设置：用户表ID
     * 表字段：middle_user_department.user_id
     * </pre>
     *
     * @param userId
     *            middle_user_department.user_id：用户表ID
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * <pre>
     * 获取：部门表ID
     * 表字段：middle_user_department.dept_id
     * </pre>
     *
     * @return middle_user_department.dept_id：部门表ID
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * <pre>
     * 设置：部门表ID
     * 表字段：middle_user_department.dept_id
     * </pre>
     *
     * @param deptId
     *            middle_user_department.dept_id：部门表ID
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    /**
     * <pre>
     * 获取：部门密保等级(0-特级,1-一级,2-二级,3-三级,4-四级)
     * 表字段：middle_user_department.encry_level_dept
     * </pre>
     *
     * @return middle_user_department.encry_level_dept：部门密保等级(0-特级,1-一级,2-二级,3-三级,4-四级)
     */
    public Integer getEncryLevelDept() {
        return encryLevelDept;
    }

    /**
     * <pre>
     * 设置：部门密保等级(0-特级,1-一级,2-二级,3-三级,4-四级)
     * 表字段：middle_user_department.encry_level_dept
     * </pre>
     *
     * @param encryLevelDept
     *            middle_user_department.encry_level_dept：部门密保等级(0-特级,1-一级,2-二级,3-三级,4-四级)
     */
    public void setEncryLevelDept(Integer encryLevelDept) {
        this.encryLevelDept = encryLevelDept;
    }

    /**
     * <pre>
     * 获取：同一用户不同部门区分标识
     * 表字段：middle_user_department.diff_dept_group
     * </pre>
     *
     * @return middle_user_department.diff_dept_group：同一用户不同部门区分标识
     */
    public String getDiffDeptGroup() {
        return diffDeptGroup;
    }

    /**
     * <pre>
     * 设置：同一用户不同部门区分标识
     * 表字段：middle_user_department.diff_dept_group
     * </pre>
     *
     * @param diffDeptGroup
     *            middle_user_department.diff_dept_group：同一用户不同部门区分标识
     */
    public void setDiffDeptGroup(String diffDeptGroup) {
        this.diffDeptGroup = diffDeptGroup == null ? null : diffDeptGroup.trim();
    }
}